version: "3.0"
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.autobus-core
    links:
      - nats
    environment:
      - AUTOBUS_CORE_NATS_URL=nats://nats:4222

  web:
    build:
      context: .
      dockerfile: Dockerfile.autobus-web
    links:
      - postgres

  platform:
    build:
      context: .
      dockerfile: Dockerfile.autobus-platform
    links:
      - nats
      - postgres
    environment:
      - AUTOBUS_PLATFORM_NATS_URL=nats://nats:4222

  nats:
    image: nats:0.9.6

  postgres:
    image: postgres:9.6