version: "3.0"
services:

  core:
    build:
      context: .
      dockerfile: Dockerfile.autobus-core
    links:
      - nats
    depends_on:
      - nats

  web:
    build:
      context: .
      dockerfile: Dockerfile.autobus-web
    links:
      - mongo
    depends_on:
      - mongo

  platform:
    build:
      context: .
      dockerfile: Dockerfile.autobus-platform
    links:
      - nats
      - mongo
    depends_on:
      - mongo
      - nats
      - core

  nats:
    image: nats:0.9.6

  mongo:
    image: mongo:3.0
    