version: "3.0"
services:
    core:
        ports:
            - "9009:9009"
        restart: on-failure
    web:
        ports:
            - "80:80"
        environment:
            AUTOBUS_WEB_MONGO_URL: mongo:27017
            AUTOBUS_WEB_HOST: 0.0.0.0:80
        restart: on-failure
    platform:
        environment:
            AUTOBUS_PLATFORM_MONGO_URL: mongo:27017
        restart: on-failure
    mongo:
        restart: always
