// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=web/design
// --out=$(GOPATH)/src/web
// --version=v1.1.0-dirty
//
// API "autobus-web": swagger TestHelpers
//
// The content of this file is auto-generated, DO NOT MODIFY

package test
