// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=web/design
// --out=$(GOPATH)/src/web
// --version=v1.1.0-dirty
//
// API "autobus-web": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

// The GPS data received by the core Autobus application
type gps struct {
	Date      *string `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	ID        *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	Latitude  *string `form:"latitude,omitempty" json:"latitude,omitempty" xml:"latitude,omitempty"`
	Longitude *string `form:"longitude,omitempty" json:"longitude,omitempty" xml:"longitude,omitempty"`
	Status    *string `form:"status,omitempty" json:"status,omitempty" xml:"status,omitempty"`
	Time      *string `form:"time,omitempty" json:"time,omitempty" xml:"time,omitempty"`
}

// Publicize creates Gps from gps
func (ut *gps) Publicize() *Gps {
	var pub Gps
	if ut.Date != nil {
		pub.Date = ut.Date
	}
	if ut.ID != nil {
		pub.ID = ut.ID
	}
	if ut.Latitude != nil {
		pub.Latitude = ut.Latitude
	}
	if ut.Longitude != nil {
		pub.Longitude = ut.Longitude
	}
	if ut.Status != nil {
		pub.Status = ut.Status
	}
	if ut.Time != nil {
		pub.Time = ut.Time
	}
	return &pub
}

// The GPS data received by the core Autobus application
type Gps struct {
	Date      *string `form:"date,omitempty" json:"date,omitempty" xml:"date,omitempty"`
	ID        *string `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	Latitude  *string `form:"latitude,omitempty" json:"latitude,omitempty" xml:"latitude,omitempty"`
	Longitude *string `form:"longitude,omitempty" json:"longitude,omitempty" xml:"longitude,omitempty"`
	Status    *string `form:"status,omitempty" json:"status,omitempty" xml:"status,omitempty"`
	Time      *string `form:"time,omitempty" json:"time,omitempty" xml:"time,omitempty"`
}
