// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=web/design
// --out=$(GOPATH)/src/web
// --version=v1.1.0-dirty
//
// API "autobus-web": BusStop Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"bytes"
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// CreateBusStopPath computes a request path to the create action of BusStop.
func CreateBusStopPath() string {

	return fmt.Sprintf("/stops")
}

// CreateBusStop makes a request to the create action endpoint of the BusStop resource
func (c *Client) CreateBusStop(ctx context.Context, path string, payload *BusStopPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateBusStopRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateBusStopRequest create the request corresponding to the create action endpoint of the BusStop resource.
func (c *Client) NewCreateBusStopRequest(ctx context.Context, path string, payload *BusStopPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType != "*/*" {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// NearestBusStopPath computes a request path to the nearest action of BusStop.
func NearestBusStopPath() string {

	return fmt.Sprintf("/stops")
}

// NearestBusStop makes a request to the nearest action endpoint of the BusStop resource
func (c *Client) NearestBusStop(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewNearestBusStopRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewNearestBusStopRequest create the request corresponding to the nearest action endpoint of the BusStop resource.
func (c *Client) NewNearestBusStopRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
