// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=web/design
// --out=$(GOPATH)/src/web
// --version=v1.1.0-dirty
//
// API "autobus-web": GPS Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// ShowGPSPath computes a request path to the show action of GPS.
func ShowGPSPath() string {

	return fmt.Sprintf("/gps")
}

// ShowGPS makes a request to the show action endpoint of the GPS resource
func (c *Client) ShowGPS(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowGPSRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowGPSRequest create the request corresponding to the show action endpoint of the GPS resource.
func (c *Client) NewShowGPSRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
